import { useState } from 'react';
import { Link } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { reportsApi } from '../../lib/api';
import { formatDate, downloadBlob } from '../../lib/utils';
import { FileText, Plus, Download, Eye, Loader2 } from 'lucide-react';

export default function ReportsPage() {
  const { data, isLoading } = useQuery({ queryKey: ['reports'], queryFn: () => reportsApi.list().then(r => r.data.data) });
  const [exporting, setExporting] = useState<string | null>(null);

  const handleExport = async (id: string, title: string) => {
    setExporting(id);
    try { const r = await reportsApi.export(id); downloadBlob(r.data, `${title}-${Date.now()}.csv`); } catch {}
    setExporting(null);
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <div>
          <h1 className="page-title flex items-center gap-2"><FileText size={22} className="text-primary-600" />Reports</h1>
          <p className="page-subtitle">Generate and download national MSME and BDSP performance reports</p>
        </div>
        <Link href="/reports/generate"><a className="btn-primary btn-sm gap-1.5"><Plus size={14} />Generate Report</a></Link>
      </div>

      {/* Quick Generate Cards */}
      <div className="grid md:grid-cols-3 gap-4 mb-8">
        {[
          { title: 'National Overview', desc: 'Complete national MSME and BDSP database summary', type: 'NATIONAL_OVERVIEW', color: 'blue' },
          { title: 'County Performance', desc: 'MSME registration progress by county', type: 'COUNTY_PERFORMANCE', color: 'green' },
          { title: 'Youth & Women', desc: 'Inclusion indicators and entrepreneurship tracking', type: 'YOUTH_WOMEN', color: 'red' },
          { title: 'Sector Analysis', desc: 'Distribution of MSMEs across economic sectors', type: 'SECTOR_ANALYSIS', color: 'amber' },
          { title: 'Workflow Pipeline', desc: 'Records by approval stage and pending actions', type: 'WORKFLOW_PIPELINE', color: 'blue' },
          { title: 'Employment Impact', desc: 'Employment generation and female/youth employment', type: 'EMPLOYMENT', color: 'green' },
        ].map(r => (
          <Link key={r.type} href={`/reports/generate?type=${r.type}`}>
            <a className={`card p-5 hover:shadow-card-hover hover:-translate-y-0.5 transition-all cursor-pointer border-l-4 ${r.color==='blue'?'border-l-primary-600':r.color==='green'?'border-l-success-600':r.color==='red'?'border-l-accent-600':'border-l-warning-600'}`}>
              <h3 className="font-semibold text-foreground text-sm mb-1">{r.title}</h3>
              <p className="text-xs text-muted-foreground">{r.desc}</p>
              <p className="text-xs text-primary-600 font-medium mt-3">Generate →</p>
            </a>
          </Link>
        ))}
      </div>

      {/* Report History */}
      <div className="card">
        <div className="card-header"><p className="card-title">Report History</p></div>
        <div className="overflow-x-auto">
          <table className="data-table">
            <thead><tr><th>Title</th><th>Type</th><th>Period</th><th>Generated By</th><th>Generated At</th><th className="text-right">Actions</th></tr></thead>
            <tbody>
              {isLoading ? (
                Array.from({length:5}).map((_,i)=><tr key={i}>{Array.from({length:6}).map((_,j)=><td key={j}><div className="skeleton h-4 rounded" /></td>)}</tr>)
              ) : (data||[]).length===0 ? (
                <tr><td colSpan={6} className="text-center py-12">
                  <FileText size={40} className="text-muted-foreground/30 mx-auto mb-3" />
                  <p className="text-muted-foreground">No reports generated yet</p>
                  <Link href="/reports/generate"><a className="btn-primary btn-sm mt-3 inline-flex"><Plus size={14}/>Generate First Report</a></Link>
                </td></tr>
              ) : (data||[]).map((r:any)=>(
                <tr key={r.id}>
                  <td className="font-medium">{r.title}</td>
                  <td><span className="chip chip-blue text-xs">{r.reportType?.replace(/_/g,' ')}</span></td>
                  <td className="text-sm text-muted-foreground">{r.period||'All time'}</td>
                  <td className="text-sm">{r.generatedBy?.firstName} {r.generatedBy?.lastName}</td>
                  <td className="text-xs text-muted-foreground">{formatDate(r.createdAt,'datetime')}</td>
                  <td>
                    <div className="flex items-center justify-end gap-1">
                      <Link href={`/reports/${r.id}`}><a className="btn-ghost btn-sm p-1.5"><Eye size={14}/></a></Link>
                      <button onClick={()=>handleExport(r.id,r.title)} disabled={exporting===r.id} className="btn-ghost btn-sm p-1.5">
                        {exporting===r.id?<Loader2 size={14} className="animate-spin"/>:<Download size={14}/>}
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
