import { useQuery } from '@tanstack/react-query';
import { Link } from 'wouter';
import { reportsApi } from '../../lib/api';
import { formatDate, formatNumber, downloadBlob } from '../../lib/utils';
import { ArrowLeft, Download, Building2, Users2, TrendingUp, UserCheck } from 'lucide-react';

export default function ReportDetailPage({ id }: { id: string }) {
  const { data: report, isLoading } = useQuery({ queryKey: ['report', id], queryFn: () => reportsApi.getById(id).then(r => r.data.data) });
  const handleExport = async () => { try { const r = await reportsApi.export(id); downloadBlob(r.data, `report-${id}-${Date.now()}.csv`); } catch {} };

  if (isLoading) return <div className="page-container"><div className="space-y-4">{Array.from({length:5}).map((_,i)=><div key={i} className="skeleton h-24 rounded-xl"/>)}</div></div>;
  if (!report) return <div className="page-container"><p className="text-muted-foreground">Report not found.</p></div>;

  const summary = report.summaryData;

  return (
    <div className="page-container max-w-4xl">
      <div className="flex items-start gap-4 mb-6">
        <Link href="/reports"><a className="btn-ghost p-2"><ArrowLeft size={18}/></a></Link>
        <div className="flex-1">
          <h1 className="text-2xl font-bold">{report.title}</h1>
          <p className="text-muted-foreground text-sm mt-1">
            {report.reportType?.replace(/_/g,' ')} • {report.period?.replace(/_/g,' ')} • Generated by {report.generatedBy?.firstName} {report.generatedBy?.lastName} on {formatDate(report.createdAt,'datetime')}
          </p>
        </div>
        <button onClick={handleExport} className="btn-secondary btn-sm gap-1.5 no-print"><Download size={14}/>Export CSV</button>
      </div>

      {/* Summary KPIs */}
      {summary && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            {[
              { label: 'Total MSMEs', value: summary.totalMSMEs, icon: Building2, color: 'text-primary-700' },
              { label: 'Approved', value: summary.approvedMSMEs, icon: Building2, color: 'text-success-600' },
              { label: 'Total BDSPs', value: summary.totalBDSPs, icon: Users2, color: 'text-info-600' },
              { label: 'Total Employment', value: summary.employmentTotal, icon: UserCheck, color: 'text-primary-700' },
            ].map(s => (
              <div key={s.label} className="card p-4 text-center">
                <s.icon size={20} className={`${s.color} mx-auto mb-2`} />
                <p className="text-2xl font-black">{formatNumber(s.value||0)}</p>
                <p className="text-xs text-muted-foreground">{s.label}</p>
              </div>
            ))}
          </div>

          {/* Youth & Women */}
          {(summary.youthLed || summary.womenLed) && (
            <div className="card mb-6">
              <div className="card-header"><p className="card-title">Inclusion Indicators</p></div>
              <div className="card-body grid grid-cols-2 gap-4 text-center">
                <div className="bg-amber-50 rounded-lg p-4">
                  <p className="text-3xl font-black text-amber-700">{formatNumber(summary.youthLed||0)}</p>
                  <p className="text-sm text-muted-foreground">Youth-Led MSMEs</p>
                  <p className="text-xs text-amber-600 mt-1">{summary.totalMSMEs ? `${((summary.youthLed/summary.totalMSMEs)*100).toFixed(1)}%` : '—'} of total</p>
                </div>
                <div className="bg-red-50 rounded-lg p-4">
                  <p className="text-3xl font-black text-red-700">{formatNumber(summary.womenLed||0)}</p>
                  <p className="text-sm text-muted-foreground">Women-Led MSMEs</p>
                  <p className="text-xs text-red-600 mt-1">{summary.totalMSMEs ? `${((summary.womenLed/summary.totalMSMEs)*100).toFixed(1)}%` : '—'} of total</p>
                </div>
              </div>
            </div>
          )}

          {/* County Breakdown */}
          {summary.countyBreakdown?.length > 0 && (
            <div className="card mb-6">
              <div className="card-header"><p className="card-title">County Breakdown</p></div>
              <div className="overflow-x-auto">
                <table className="data-table">
                  <thead><tr><th>County</th><th>Total MSMEs</th><th>Approved</th><th>Verified</th><th>Pending</th><th>Youth-Led</th><th>Women-Led</th></tr></thead>
                  <tbody>
                    {summary.countyBreakdown.map((c:any) => (
                      <tr key={c.county}><td className="font-medium">{c.county}</td><td className="text-center">{formatNumber(c.total||0)}</td><td className="text-center text-success-600 font-medium">{formatNumber(c.approved||0)}</td><td className="text-center">{formatNumber(c.verified||0)}</td><td className="text-center text-amber-600">{formatNumber(c.pending||0)}</td><td className="text-center text-amber-700">{formatNumber(c.youth||0)}</td><td className="text-center text-red-700">{formatNumber(c.women||0)}</td></tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Sector Breakdown */}
          {summary.sectorBreakdown?.length > 0 && (
            <div className="card">
              <div className="card-header"><p className="card-title">Sector Breakdown</p></div>
              <div className="overflow-x-auto">
                <table className="data-table">
                  <thead><tr><th>Sector</th><th>Total MSMEs</th><th>%</th></tr></thead>
                  <tbody>
                    {summary.sectorBreakdown.map((s:any) => (
                      <tr key={s.sector}><td className="font-medium">{s.sector}</td><td className="text-center">{formatNumber(s.total||0)}</td>
                        <td><div className="progress-bar"><div className="progress-fill" style={{width:`${summary.totalMSMEs?Math.round((s.total/summary.totalMSMEs)*100):0}%`}}/></div></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
