steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/sba-msme-portal-lr/sba-registry/frontend:latest'
      - '-f'
      - 'apps/frontend/Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=https://sba-backend-800876397176.us-central1.run.app/api'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/sba-msme-portal-lr/sba-registry/frontend:latest'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
